name: "🛠️ Build"
description: "CICD 및 인프라, 빌드 관련 작업"
labels: ["build"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 설명을 작성해 주세요.
      placeholder: 예시) Dockerfile 및 nginx 설정 추가
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 작성해주세요.
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true